// assets/components/BookCreate.jsx
// assets/components/BookCreate.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function BookCreate() {
    const navigate = useNavigate();
    const [formData, setFormData] = useState({
        title: '',
        author: '',
        description: '',
        publish_date: '',
        price: ''
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: value
        }));
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        fetch('/api/books/', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(formData)
        })
            .then((res) => {
                if (res.ok) {
                    navigate('/books');
                } else {
                    console.error('Eroare la crearea cărții');
                }
            })
            .catch(error => console.error(error));
    };

    return (
        <div>
            <h2>Adaugă o carte</h2>
            <form onSubmit={handleSubmit}>
                <div>
                    <label>Titlu</label>
                    <input
                        type="text"
                        name="title"
                        value={formData.title}
                        onChange={handleChange}
                        required
                    />
                </div>
                <div>
                    <label>Autor</label>
                    <input
                        type="text"
                        name="author"
                        value={formData.author}
                        onChange={handleChange}
                        required
                    />
                </div>
                <div>
                    <label>Descriere</label>
                    <textarea
                        name="description"
                        value={formData.description}
                        onChange={handleChange}
                        required
                    />
                </div>
                <div>
                    <label>Data publicării</label>
                    <input
                        type="date"
                        name="publish_date"
                        value={formData.publish_date}
                        onChange={handleChange}
                        required
                    />
                </div>
                <div>
                    <label>Preț</label>
                    <input
                        type="number"
                        step="0.01"
                        name="price"
                        value={formData.price}
                        onChange={handleChange}
                        required
                    />
                </div>
                <button type="submit">Salvează</button>
            </form>
        </div>
    );
}

export default BookCreate;

// assets/pages/BookCreate.vue
<template>
  <div>
    <h2>➕ Adaugă carte nouă</h2>

    <form @submit.prevent="submitForm">
      <label>Titlu:</label>
      <input v-model="book.title" required />

      <label>Autor:</label>
      <input v-model="book.author" required />

      <label>Descriere:</label>
      <textarea v-model="book.description"></textarea>

      <label>Data publicării:</label>
      <input type="date" v-model="book.publish_date" required />

      <label>Preț:</label>
      <input type="number" v-model="book.price" step="0.01" required />

      <button type="submit">✅ Salvează</button>
    </form>
  </div>
</template>

<script>
import { isAdmin } from '../utils/auth'
import { useRouter } from 'vue-router'

export default {
  name: 'BookCreate',
  data() {
    return {
      book: {
        title: '',
        author: '',
        description: '',
        publish_date: '',
        price: 0
      }
    }
  },
  setup() {
    const router = useRouter()
    return { router }
  },
  methods: {
    async submitForm() {
      if (!isAdmin()) {
        alert('Acces interzis.')
        return
      }

      const response = await fetch('/api/books/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json' ,
          'Authorization': 'Bearer ' + localStorage.getItem('token')
        },
        body: JSON.stringify(this.book)
      })

      if (response.ok) {
        alert('Carte adăugată!')
        this.$router.push('/')
      } else {
        alert('Eroare la salvare.')
      }
    }
  }
}
</script>
