// assets/components/BookList.jsx
// assets/components/BookList.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

function BookList() {
    const [books, setBooks] = useState([]);

    useEffect(() => {
        fetch('/api/books')
            .then((res) => res.json())
            .then((data) => setBooks(data))
            .catch((error) => console.error(error));
    }, []);

    return (
        <div>
            <h2>Lista de Cărți</h2>
            <Link to="/books/new">Adaugă o carte nouă</Link>
            <ul>
                {books.map(book => (
                    <li key={book.id}>
                        <Link to={`/books/${book.id}`}>
                            {book.title} - {book.author}
                        </Link>
                    </li>
                ))}
            </ul>
        </div>
    );
}

export default BookList;

// assets/pages/BookList.vue
<template>
  <div>
    <h2>Lista Cărților</h2>

    <router-link v-if="isAdmin()" to="/books/new">➕ Adaugă carte</router-link>

    <ul v-if="books.length">
      <li v-for="book in books" :key="book.id">
        <strong>{{ book.title }}</strong> de {{ book.author }}
        |
        <router-link :to="`/books/${book.id}`">Detalii</router-link>
        <template v-if="isAdmin()">
          | <router-link :to="`/books/${book.id}/edit`">Editează</router-link>
          | <button @click="deleteBook(book.id)">🗑️</button>
        </template>
      </li>
    </ul>

    <p v-else>Nu există cărți.</p>
  </div>
</template>

<script>
import { isAdmin } from '../utils/auth'

export default {
  name: 'BookList',
  data() {
    return {
      books: []
    }
  },
  mounted() {
    fetch('/api/books')
        .then(res => res.json())
        .then(data => {
          this.books = data
        })
        .catch(err => console.error('Eroare la încărcare:', err))
  },
  methods: {
    deleteBook(id) {
      if (!confirm('Sigur dorești să ștergi această carte?')) return

      fetch(`/api/books/${id}`, {
        method: 'DELETE',
        headers:{
          'Authorization': 'Bearer ' + localStorage.getItem('token')
        }
      })
          .then(() => {
            this.books = this.books.filter(book => book.id !== id)
          })
          .catch(err => console.error('Eroare la ștergere:', err))
    },
    isAdmin
  }
}
</script>
